server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React Router fallback（关键）
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 后端 API 转发（假设 Python 跑在 5000）
    location /api/ {
        proxy_pass http://127.0.0.1:38888/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        access_log off;

        # Buffer Settings
        client_max_body_size 100m;
        client_body_buffer_size 10m;
        proxy_request_buffering off;
        proxy_buffering off;
        gzip off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}